"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import PlatformShell from "./PlatformShell";
import { supabase } from "@/lib/supabase";

export default function PlatformPage() { const [data, setData] = useState<any>(null); const [error, setError] = useState(""); useEffect(() => { void load(); async function load() { const { data: { session } } = await supabase.auth.getSession(); const response = await fetch("/api/platform/overview", { headers: { Authorization: `Bearer ${session?.access_token || ""}` } }); const value = await response.json(); if (!response.ok) setError(value.error || "Unable to load platform data."); else setData(value); } }, []); return <PlatformShell><PageHeader title="SiteQube Platform" subtitle="Manage organizations, access, domains, and platform configuration." />{error ? <ErrorBox message={error} /> : !data ? <Loading /> : <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Organizations", data.metrics.organizations], ["Managed organizations", data.organizations.filter((org: any) => org.entitlementMode === "Managed").length], ["Configured domains", data.metrics.configuredDomains], ["Legacy organizations", data.organizations.filter((org: any) => org.entitlementMode !== "Managed").length]].map(([label, value]) => <div key={label} className="rounded-xl border bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-3 text-3xl font-semibold">{value}</p></div>)}</div><section className="mt-8 rounded-xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">Organizations</h2><p className="text-sm text-slate-500">A clear view of every SiteQube organization.</p></div><Link href="/platform/organizations" className="text-sm font-semibold text-slate-700 hover:underline">View all</Link></div><div className="mt-5 space-y-3">{data.organizations.slice(0, 5).map((org: any) => <OrgRow key={org.id} org={org} />)}</div></section></>}</PlatformShell>; }
function PageHeader({ title, subtitle }: { title: string; subtitle: string }) { return <div className="mb-8"><p className="text-sm font-semibold text-slate-500">SITEQUBE PLATFORM</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{title}</h1><p className="mt-2 text-slate-500">{subtitle}</p></div>; }
function OrgRow({ org }: { org: any }) { return <Link href={`/platform/organizations/${org.id}`} className="flex flex-col gap-3 rounded-lg border p-4 hover:border-slate-400 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-3"><p className="font-semibold">{org.name}</p><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-medium text-emerald-700">{org.status || "Active"}</span></div><p className="mt-1 text-sm text-slate-500">{org.code || "No organization code"}</p></div><div className="flex items-center gap-2 text-xs"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-slate-600">{org.entitlementMode === "Managed" ? "Managed" : "Legacy"}</span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-slate-600">{org.domainStatus === "Configured" ? "Domain configured" : "No domain"}</span></div></Link>; }
function Loading() { return <div className="rounded-xl border bg-white p-8 text-sm text-slate-500">Loading platform metadata...</div>; }
function ErrorBox({ message }: { message: string }) { return <div className="rounded-xl border border-red-200 bg-red-50 p-5 text-sm text-red-700">{message}</div>; }
