"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Building2, Globe2, LayoutDashboard, Menu, Settings2, ShieldCheck, UsersRound, X } from "lucide-react";
import { useState } from "react";

const links = [["Overview", "/platform", LayoutDashboard, true], ["Organizations", "/platform/organizations", Building2, true], ["Default Roles", "/platform/role-templates", ShieldCheck, true], ["Plans & Modules", "#", Settings2, false], ["Domains", "#", Globe2, false], ["Platform Access", "#", UsersRound, false]] as const;

export default function PlatformShell({ children }: { children: React.ReactNode }) {
  const pathname = usePathname(); const [open, setOpen] = useState(false);
  return <div className="min-h-screen bg-slate-50 text-slate-950"><header className="flex h-16 items-center justify-between border-b bg-white px-4 sm:px-8"><Link href="/platform" className="flex items-center gap-3 font-semibold tracking-tight"><span className="grid h-9 w-9 place-items-center rounded-lg bg-slate-950 text-sm text-white">S</span><span>SiteQube <span className="font-normal text-slate-500">Platform</span></span></Link><div className="flex items-center gap-3"><span className="hidden text-sm font-medium text-slate-600 sm:inline">Platform Owner</span><Link href="/" className="rounded-md border px-3 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50">Back to ERP</Link><button aria-label="Open platform navigation" className="rounded-md p-2 hover:bg-slate-100 md:hidden" onClick={() => setOpen(true)}><Menu size={20} /></button></div></header><div className="mx-auto flex max-w-[1440px]"><aside className={`${open ? "fixed inset-y-0 left-0 z-20 w-72 shadow-xl" : "hidden"} border-r bg-white p-5 md:sticky md:top-0 md:block md:h-[calc(100vh-4rem)] md:w-60 md:shrink-0`}><div className="mb-6 flex items-center justify-between md:block"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-400">Platform control plane</p><button aria-label="Close platform navigation" className="rounded-md p-2 hover:bg-slate-100 md:hidden" onClick={() => setOpen(false)}><X size={18} /></button></div><nav className="space-y-1">{links.map(([label, href, Icon, active]) => active ? <Link key={label} href={href} onClick={() => setOpen(false)} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium ${pathname === href ? "bg-slate-950 text-white" : "text-slate-600 hover:bg-slate-100"}`}><Icon size={17} />{label}</Link> : <div key={label} className="flex items-center justify-between gap-2 rounded-lg px-3 py-2.5 text-sm text-slate-400"><span className="flex items-center gap-3"><Icon size={17} />{label}</span><span className="text-[10px] uppercase tracking-wide">Soon</span></div>)}</nav></aside>{open && <button aria-label="Close navigation overlay" className="fixed inset-0 z-10 bg-slate-950/20 md:hidden" onClick={() => setOpen(false)} />}<main className="min-w-0 flex-1 p-4 sm:p-8">{children}</main></div></div>;
}
