export type HrDepartment = {
  id: string;
  organization_id?: string;
  department_name: string;
  department_code?: string | null;
  status?: string | null;
};

export type HrDesignation = {
  id: string;
  organization_id?: string;
  department_id?: string | null;
  designation_name: string;
  designation_code?: string | null;
  status?: string | null;
};

export type HrEmployee = {
  id: string;
  organization_id: string;
  company_id: string;
  site_id?: string | null;
  employee_code: string;
  employee_name: string;
  email?: string | null;
  phone?: string | null;
  personal_email?: string | null;
  personal_phone?: string | null;
  date_of_birth?: string | null;
  gender?: string | null;
  nationality?: string | null;
  father_name?: string | null;
  mother_name?: string | null;
  spouse_name?: string | null;
  blood_group?: string | null;
  marital_status?: string | null;
  current_address?: string | null;
  permanent_address?: string | null;
  current_address_line1?: string | null;
  current_address_line2?: string | null;
  current_address_city?: string | null;
  current_address_state?: string | null;
  current_address_country?: string | null;
  current_address_pin_code?: string | null;
  permanent_address_line1?: string | null;
  permanent_address_line2?: string | null;
  permanent_address_city?: string | null;
  permanent_address_state?: string | null;
  permanent_address_country?: string | null;
  permanent_address_pin_code?: string | null;
  emergency_contact_name?: string | null;
  emergency_contact_phone?: string | null;
  emergency_contact_relationship?: string | null;
  remarks?: string | null;
  department_id?: string | null;
  designation_id?: string | null;
  reporting_manager_id?: string | null;
  user_id?: string | null;
  date_of_joining?: string | null;
  employment_type?: string | null;
  shift?: string | null;
  confirmation_date?: string | null;
  notice_period_from?: string | null;
  notice_period_to?: string | null;
  resignation_date?: string | null;
  date_of_exit?: string | null;
  exit_remark?: string | null;
  status?: string | null;
  photo_storage_path?: string | null;
  photo_updated_at?: string | null;
  photo_signed_url?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
};

export type HrEmployeeUserOption = {
  id: string;
  email?: string | null;
  full_name?: string | null;
  status?: string | null;
  linked_employee_id?: string | null;
  role_summary?: string | null;
};

export type EmployeeDocument = {
  id: string;
  employee_id: string;
  document_type?: string | null;
  document_name?: string | null;
  file_name?: string | null;
  document_number?: string | null;
  metadata?: Record<string, unknown> | null;
  issue_date?: string | null;
  expiry_date?: string | null;
  issuing_authority?: string | null;
  issue_country?: string | null;
  issue_state?: string | null;
  remarks?: string | null;
  version?: number | null;
  is_active?: boolean | null;
  replaced_by_document_id?: string | null;
  mime_type?: string | null;
  file_size?: number | null;
  uploaded_by_name?: string | null;
  uploaded_by_email?: string | null;
  uploaded_at?: string | null;
  signed_url?: string | null;
  signed_url_error?: string | null;
};

export type EmployeeComplianceRecord = {
  id: string;
  organization_id: string;
  employee_id: string;
  record_type: string;
  record_number?: string | null;
  record_name?: string | null;
  issue_date?: string | null;
  expiry_date?: string | null;
  issuing_authority?: string | null;
  metadata?: Record<string, unknown> | null;
  source?: string | null;
  status?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
};

export type EmployeeEmploymentHistory = {
  id: string;
  organization_id: string;
  employee_id: string;
  event_type: string;
  event_date: string;
  effective_from?: string | null;
  effective_to?: string | null;
  title?: string | null;
  description?: string | null;
  reason?: string | null;
  source: string;
  is_manual?: boolean | null;
  previous_values?: Record<string, unknown> | null;
  new_values?: Record<string, unknown> | null;
  company_id?: string | null;
  site_id?: string | null;
  department_id?: string | null;
  designation_id?: string | null;
  reporting_manager_id?: string | null;
  employment_type?: string | null;
  shift?: string | null;
  employment_status?: string | null;
  reference_document_id?: string | null;
  source_system?: string | null;
  source_record_id?: string | null;
  import_batch_id?: string | null;
  created_by_name?: string | null;
  created_by_email?: string | null;
  created_at?: string | null;
  updated_by_name?: string | null;
  updated_by_email?: string | null;
  updated_at?: string | null;
};

export type EmployeeSalaryHistory = {
  id: string;
  organization_id: string;
  employee_id: string;
  revision_no: number;
  effective_from: string;
  effective_to?: string | null;
  reason?: string | null;
  remarks?: string | null;
  revision_type: string;
  status: string;
  basic_salary?: number | null;
  gross_salary?: number | null;
  net_salary?: number | null;
  ctc?: number | null;
  employee_pf?: number | null;
  employer_pf?: number | null;
  employee_esic?: number | null;
  employer_esic?: number | null;
  professional_tax?: number | null;
  tds?: number | null;
  other_salary_deductions?: number | null;
  bonus?: number | null;
  previous_values?: Record<string, unknown> | null;
  new_values?: Record<string, unknown> | null;
  source?: string | null;
  source_system?: string | null;
  source_record_id?: string | null;
  import_batch_id?: string | null;
  created_by_name?: string | null;
  created_by_email?: string | null;
  created_at?: string | null;
  updated_by_name?: string | null;
  updated_by_email?: string | null;
  updated_at?: string | null;
};

export type ErpAuditLog = {
  id: string;
  organization_id?: string | null;
  company_id?: string | null;
  site_id?: string | null;
  module_code: string;
  entity_type: string;
  record_id?: string | null;
  parent_entity_type?: string | null;
  parent_record_id?: string | null;
  action: string;
  description?: string | null;
  old_values?: Record<string, unknown> | null;
  new_values?: Record<string, unknown> | null;
  ip_address?: string | null;
  user_agent?: string | null;
  browser?: string | null;
  device_type?: string | null;
  source?: string | null;
  import_batch_id?: string | null;
  created_by?: string | null;
  created_by_name?: string | null;
  created_by_email?: string | null;
  created_at: string;
};

export type ReimbursementClaim = {
  id: string;
  organization_id: string;
  company_id: string;
  site_id?: string | null;
  employee_id: string;
  claim_number: string;
  claim_date: string;
  claim_type?: string | null;
  description?: string | null;
  amount: number;
  gst_amount: number;
  total_amount: number;
  approved_amount?: number | null;
  status: string;
  approval_status?: string | null;
  submitted_at?: string | null;
  approved_by_name?: string | null;
  approved_by_email?: string | null;
  approved_at?: string | null;
  rejected_by_name?: string | null;
  rejected_by_email?: string | null;
  rejected_at?: string | null;
  rejection_reason?: string | null;
  payment_id?: string | null;
  drive_sync_status?: string | null;
  drive_sync_error?: string | null;
  created_by_name?: string | null;
  created_by_email?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
};

export type ReimbursementDocument = {
  id: string;
  reimbursement_claim_id: string;
  document_type?: string | null;
  file_name?: string | null;
  mime_type?: string | null;
  uploaded_at?: string | null;
  uploaded_by_name?: string | null;
  uploaded_by_email?: string | null;
  signed_url?: string | null;
  signed_url_error?: string | null;
};

export type ReimbursementHistoryRow = {
  id: string;
  reimbursement_claim_id: string;
  from_status?: string | null;
  to_status: string;
  action: string;
  remarks?: string | null;
  changed_by_name?: string | null;
  changed_by_email?: string | null;
  changed_at: string;
};

export type LookupOption = {
  id: string;
  label: string;
  meta?: string;
};
