import { deflateRawSync } from "node:zlib";

function xml(value: unknown) { return String(value ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;"); }
function cellRef(column: number, row: number) { let name = "", n = column; while (n > 0) { const remainder = (n - 1) % 26; name = String.fromCharCode(65 + remainder) + name; n = Math.floor((n - 1) / 26); } return `${name}${row}`; }
function crc32(data: Buffer) { let crc = 0xffffffff; for (const byte of data) { crc ^= byte; for (let bit = 0; bit < 8; bit += 1) crc = (crc >>> 1) ^ (crc & 1 ? 0xedb88320 : 0); } return (crc ^ 0xffffffff) >>> 0; }
function zip(entries: Array<[string, Buffer]>) { const local: Buffer[] = [], central: Buffer[] = []; let offset = 0; for (const [name, input] of entries) { const nameBuffer = Buffer.from(name), data = deflateRawSync(input), header = Buffer.alloc(30); header.writeUInt32LE(0x04034b50, 0); header.writeUInt16LE(20, 4); header.writeUInt16LE(8, 6); header.writeUInt32LE(crc32(input), 14); header.writeUInt32LE(data.length, 18); header.writeUInt32LE(input.length, 22); header.writeUInt16LE(nameBuffer.length, 26); local.push(header, nameBuffer, data); const directory = Buffer.alloc(46); directory.writeUInt32LE(0x02014b50, 0); directory.writeUInt16LE(20, 4); directory.writeUInt16LE(20, 6); directory.writeUInt16LE(8, 10); directory.writeUInt32LE(crc32(input), 16); directory.writeUInt32LE(data.length, 20); directory.writeUInt32LE(input.length, 24); directory.writeUInt16LE(nameBuffer.length, 28); directory.writeUInt32LE(offset, 42); central.push(directory, nameBuffer); offset += header.length + nameBuffer.length + data.length; } const centralBuffer = Buffer.concat(central), end = Buffer.alloc(22); end.writeUInt32LE(0x06054b50, 0); end.writeUInt16LE(entries.length, 8); end.writeUInt16LE(entries.length, 10); end.writeUInt32LE(centralBuffer.length, 12); end.writeUInt32LE(offset, 16); return Buffer.concat([...local, centralBuffer, end]); }
function halfLabel(value: unknown) { if (value === true) return "Present"; if (value === false) return "Absent"; return "Not Filled"; }
function rowStatus(row: any) { return row.first_half_present === null || row.first_half_present === undefined || row.second_half_present === null || row.second_half_present === undefined ? "Draft / Not Filled" : row.status || "-"; }
function exportRows(rows: any[]) { return rows.map((row, index) => [index + 1, row.labour_code, row.labour_name, row.contractor_name, row.category, String(row.daily_rate_label || "-").replace(/₹/g, "Rs. "), row.work_date, halfLabel(row.first_half_present), halfLabel(row.second_half_present), Number(row.overtime_minutes || 0) / 60, Number(row.bonus_minutes || 0) / 60, rowStatus(row)]); }
function currency(value: number) { const rounded = Math.round(value * 100) / 100; return `Rs. ${rounded.toLocaleString("en-IN", { minimumFractionDigits: Number.isInteger(rounded) ? 0 : 2, maximumFractionDigits: 2 })}`; }
function reportDate(value: unknown) { const text = String(value || ""); const match = text.match(/^(\d{4})-(\d{2})-(\d{2})$/); return match ? `${match[3]}/${match[2]}/${match[1]}` : text || "-"; }
function wageRows(rows: any[]) {
  return rows.map((row, index) => {
    const dailyRate = Number(row.daily_rate ?? row.wage_rate ?? 0);
    const hourlyRate = dailyRate / 8;
    const attendance = rowStatus(row);
    const presentHalves = Number(row.first_half_present === true) + Number(row.second_half_present === true);
    const attendanceWage = presentHalves === 2 ? dailyRate : presentHalves === 1 ? dailyRate / 2 : 0;
    const otHours = Number(row.overtime_minutes || 0) / 60;
    const bonusHours = Number(row.bonus_minutes || 0) / 60;
    const otAmount = otHours * hourlyRate;
    const bonusAmount = bonusHours * hourlyRate;
    return { row, index: index + 1, dailyRate, attendance, attendanceWage, otHours, otAmount, bonusHours, bonusAmount, total: attendanceWage + otAmount + bonusAmount };
  });
}
function wageTotals(items: any[]) { return items.reduce((total, item) => ({ labour: total.labour + 1, present: total.present + (item.attendance === "present" ? 1 : 0), absent: total.absent + (item.attendance === "absent" ? 1 : 0), halfDay: total.halfDay + (item.attendance === "half_day" ? 1 : 0), attendanceWage: total.attendanceWage + item.attendanceWage, otHours: total.otHours + item.otHours, otAmount: total.otAmount + item.otAmount, bonusHours: total.bonusHours + item.bonusHours, bonusAmount: total.bonusAmount + item.bonusAmount, total: total.total + item.total }), { labour: 0, present: 0, absent: 0, halfDay: 0, attendanceWage: 0, otHours: 0, otAmount: 0, bonusHours: 0, bonusAmount: 0, total: 0 }); }
export function labourAttendanceXlsx(context: any, rows: any[]) { const values = [["Labour Attendance Register"], ["Company", context.company_name || "-"], ["Site", context.site_name || "-"], ["Attendance Date", context.work_date || "-"], ["Status", context.status || "-"], ["Submitted By", context.submitted_by_name || context.submitted_by_email || "-"], ["Submitted At", context.submitted_at || "-"], [], ["S.No.", "Labour Code", "Labour Name", "Contractor", "Category / Trade", "Daily Rate", "Attendance Date", "Submitted By", "First Half", "Second Half", "OT Hours", "Bonus Hours", "Status"], ...exportRows(rows)]; const sheetRows = values.map((row, rowIndex) => `<row r="${rowIndex + 1}">${row.map((value, columnIndex) => `<c r="${cellRef(columnIndex + 1, rowIndex + 1)}"${typeof value === "number" ? "" : " t=\"inlineStr\""}>${typeof value === "number" ? `<v>${value}</v>` : `<is><t>${xml(value)}</t></is>`}</c>`).join("")}</row>`).join(""); const sheet = `<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="9" topLeftCell="A10" state="frozen"/></sheetView></sheetViews><sheetData>${sheetRows}</sheetData></worksheet>`; return zip([["[Content_Types].xml", Buffer.from(`<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>`)], ["_rels/.rels", Buffer.from(`<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`)], ["xl/workbook.xml", Buffer.from(`<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Attendance" sheetId="1" r:id="rId1"/></sheets></workbook>`)], ["xl/_rels/workbook.xml.rels", Buffer.from(`<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>`)], ["xl/worksheets/sheet1.xml", Buffer.from(sheet)]]); }
function pdfEscape(value: string) { return value.replace(/[()\\]/g, "\\$&").replace(/[^\x20-\x7e]/g, "?"); }
function wrap(value: unknown, width: number) { const text = String(value ?? "-"); const words = text.split(/\s+/); const lines: string[] = []; let current = ""; for (const word of words) { if (!current) current = word; else if ((current.length + word.length + 1) <= width) current += ` ${word}`; else { lines.push(current); current = word; } } if (current || !lines.length) lines.push(current || "-"); return lines; }
function pdfText(x: number, y: number, text: string, size = 7, bold = false) { return `BT 0 0 0 rg /${bold ? "F2" : "F1"} ${size} Tf ${x.toFixed(1)} ${y.toFixed(1)} Td (${pdfEscape(text)}) Tj ET`; }
export function formatAttendanceExportTimestamp(value: unknown) { if (!value) return "-"; const date = new Date(String(value)); if (Number.isNaN(date.getTime())) return String(value); return new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "short", year: "numeric", hour: "numeric", minute: "2-digit", hour12: true, timeZone: "Asia/Kolkata" }).format(date); }
export function labourAttendancePdf(context: any, rows: any[]) {
  const headers = ["S.No.", "Labour Name", "Contractor", "Category / Trade", "Attendance", "OT Hrs", "Bonus Hrs", "8-Hr Rate", "OT Amount", "Bonus Amount", "Total Earned"];
  const allCalculated = wageRows(rows);
  const calculated = allCalculated.filter((item) => !(item.row.first_half_present === false && item.row.second_half_present === false));
  const values = calculated.map((item, index) => [index + 1, item.row.labour_name, item.row.contractor_name, item.row.category, item.attendance, item.otHours, item.bonusHours, currency(item.dailyRate), currency(item.otAmount), currency(item.bonusAmount), currency(item.total)]);
  const totals = wageTotals(calculated);
  const attendanceCounts = wageTotals(allCalculated);
  values.push(["", "Grand Total", "", "", "", totals.otHours, totals.bonusHours, "", currency(totals.otAmount), currency(totals.bonusAmount), currency(totals.total)]);
  const widths = [28, 105, 85, 65, 58, 48, 55, 55, 70, 75, 75];
  const left = 32, pageWidth = 792, pageHeight = 612, bottom = 38, top = 574;
  const objects: string[] = ["<< /Type /Catalog /Pages 2 0 R >>", "<< /Type /Pages /Kids [] /Count 0 >>"];
  const pageObjectIds: number[] = [];
  const makePage = (pageRows: any[][], pageNumber: number, totalPages: number) => {
    const commands: string[] = [pdfText(32, 574, "LABOUR ATTENDANCE REGISTER", 14, true), pdfText(32, 554, `Company: ${context.company_name || "-"}`, 8), pdfText(32, 542, `Site: ${context.site_name || "-"}`, 8), pdfText(32, 530, `Attendance Date / Period: ${reportDate(context.work_date)}`, 8), pdfText(32, 518, `Status: ${context.status || "-"}`, 8), pdfText(32, 506, `Submitted By: ${context.submitted_by_name || context.submitted_by_email || "-"}`, 8), pdfText(32, 494, `Submitted At: ${context.submitted_at || "-"}`, 8)];
    let y = 466;
    const drawRow = (cells: any[], header = false) => { const wrapped = cells.map((cell, index) => wrap(cell, Math.max(5, Math.floor(widths[index] / (header ? 4.8 : 5.0))))); const height = Math.max(header ? 24 : 18, Math.max(...wrapped.map((lines) => lines.length)) * 8 + 6); let x = left; cells.forEach((_, index) => { commands.push(`${header ? "0.78 0.84 0.92" : "1 1 1"} rg ${x.toFixed(1)} ${(y - height).toFixed(1)} ${widths[index]} ${height} re f 0.55 0.6 0.68 RG ${x.toFixed(1)} ${(y - height).toFixed(1)} ${widths[index]} ${height} re S`); wrapped[index].forEach((line, lineIndex) => commands.push(pdfText(x + 3, y - 10 - lineIndex * 8, line, 6.5, header))); x += widths[index]; }); y -= height; return height; };
    drawRow(headers, true); pageRows.forEach((row) => drawRow(row)); commands.push(pdfText(32, 22, `Page ${pageNumber} of ${totalPages}`, 7)); return commands.join("\n");
  };
  const pages: any[][] = [];
  let currentPage: any[][] = [];
  const headerHeight = Math.max(24, Math.max(...headers.map((header, index) => wrap(header, Math.max(5, Math.floor(widths[index] / 4.8))).length)) * 8 + 6);
  let currentY = 466 - headerHeight;
  for (const row of values) {
    const rowHeight = Math.max(18, Math.max(...row.map((cell, index) => wrap(cell, Math.max(5, Math.floor(widths[index] / 5.0))).length)) * 8 + 6);
    if (currentPage.length > 0 && currentY - rowHeight < 42) {
      pages.push(currentPage);
      currentPage = [];
      currentY = 466 - headerHeight;
    }
    currentPage.push(row);
    currentY -= rowHeight;
  }
  if (currentPage.length || !pages.length) pages.push(currentPage);
  const totalPages = pages.length;
  const contractorMap = new Map<string, any[]>();
  for (const item of calculated) { const key = item.row.contractor_name || "Unassigned"; contractorMap.set(key, [...(contractorMap.get(key) || []), item]); }
  const summaryHeaders = ["Contractor", "Labour Count", "Attendance Wage", "OT Hrs", "Bonus Hrs", "OT Amount", "Bonus Amount", "Total Earned"];
  const summaryWidths = [150, 62, 92, 52, 62, 78, 92, 90];
  const summaryRows = Array.from(contractorMap.entries()).map(([contractor, items]) => { const total = wageTotals(items); return [contractor, total.labour, currency(total.attendanceWage), total.otHours, total.bonusHours, currency(total.otAmount), currency(total.bonusAmount), currency(total.total)]; });
  summaryRows.push(["Grand Total", totals.labour, currency(totals.attendanceWage), totals.otHours, totals.bonusHours, currency(totals.otAmount), currency(totals.bonusAmount), currency(totals.total)]);
  const makeSummaryPage = (pageNumber: number, totalPageCount: number) => {
    const approvalLines = context.approved_by_name && context.approved_at ? [pdfText(32, 482, `Approved By: ${context.approved_by_name}`, 8), pdfText(32, 470, `Approved At: ${context.approved_at}`, 8)] : [];
    const commands: string[] = [pdfText(32, 574, "LABOUR ATTENDANCE REGISTER - SUMMARY", 14, true), pdfText(32, 554, `Company: ${context.company_name || "-"}`, 8), pdfText(32, 542, `Site: ${context.site_name || "-"}`, 8), pdfText(32, 530, `Attendance Date: ${reportDate(context.work_date)}`, 8), pdfText(32, 518, `Status: ${context.status || "-"}`, 8), pdfText(32, 506, `Submitted By: ${context.submitted_by_name || context.submitted_by_email || "-"}`, 8), pdfText(32, 494, `Submitted At: ${context.submitted_at || "-"}`, 8), ...approvalLines, pdfText(32, 442, `Total Labour: ${attendanceCounts.labour}    Present: ${attendanceCounts.present}    Absent: ${attendanceCounts.absent}    Half Day: ${attendanceCounts.halfDay}`, 8, true), pdfText(32, 414, "FINANCIAL GRAND TOTALS", 9, true), pdfText(32, 398, `Attendance Wage: ${currency(totals.attendanceWage)}    OT Hrs: ${totals.otHours.toFixed(2)}    Bonus Hrs: ${totals.bonusHours.toFixed(2)}`, 8), pdfText(32, 382, `OT Amount: ${currency(totals.otAmount)}    Bonus Amount: ${currency(totals.bonusAmount)}    Total Earned: ${currency(totals.total)}`, 8, true)];
    let y = 340;
    const drawSummaryRow = (cells: any[], header = false) => { const wrapped = cells.map((cell, index) => wrap(cell, Math.max(5, Math.floor(summaryWidths[index] / (header ? 4.8 : 5.0))))); const height = Math.max(header ? 24 : 18, Math.max(...wrapped.map((lines) => lines.length)) * 8 + 6); let x = left; cells.forEach((_, index) => { commands.push(`${header ? "0.78 0.84 0.92" : "1 1 1"} rg ${x.toFixed(1)} ${(y - height).toFixed(1)} ${summaryWidths[index]} ${height} re f 0.55 0.6 0.68 RG ${x.toFixed(1)} ${(y - height).toFixed(1)} ${summaryWidths[index]} ${height} re S`); wrapped[index].forEach((line, lineIndex) => commands.push(pdfText(x + 3, y - 10 - lineIndex * 8, line, 6.5, header))); x += summaryWidths[index]; }); y -= height; };
    commands.push(pdfText(32, y + 16, "CONTRACTOR SUMMARY", 9, true)); drawSummaryRow(summaryHeaders, true); summaryRows.forEach((row) => drawSummaryRow(row)); commands.push(pdfText(32, 22, `Page ${pageNumber} of ${totalPageCount}`, 7)); return commands.join("\n");
  };
  const contents = [makeSummaryPage(1, totalPages + 1), ...pages.map((pageRows, index) => makePage(pageRows, index + 2, totalPages + 1))];
  const fontId = 3 + contents.length * 2; const pageIds = contents.map((content) => { const pageId = objects.length + 1; pageObjectIds.push(pageId); objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Resources << /Font << /F1 ${fontId} 0 R /F2 ${fontId + 1} 0 R >> >> /Contents ${pageId + 1} 0 R >>`, `<< /Length ${Buffer.byteLength(content)} >>\nstream\n${content}\nendstream`); return pageId; }); objects[1] = `<< /Type /Pages /Kids [${pageIds.map((id) => `${id} 0 R`).join(" ")}] /Count ${pageIds.length} >>`; objects.push("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>", "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>"); let pdf = "%PDF-1.4\n", offsets: number[] = [0]; objects.forEach((object, index) => { offsets.push(Buffer.byteLength(pdf)); pdf += `${index + 1} 0 obj\n${object}\nendobj\n`; }); const xref = Buffer.byteLength(pdf); pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n${offsets.slice(1).map((offset) => `${String(offset).padStart(10, "0")} 00000 n \n`).join("")}trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`; return Buffer.from(pdf);
}
export function sanitizeFilename(value: unknown) { return String(value || "register").replace(/[^a-z0-9_-]+/gi, "_").replace(/^_+|_+$/g, ""); }
