"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useAccessContext } from "@/components/AccessContext";
import { apiFetch } from "@/components/hr/hrClient";
import { can } from "@/lib/accessControl";
import { supabase } from "@/lib/supabase";

const endpoint = "/api/procurement/purchase-orders/master-data";
const sourceEndpoint = "/api/procurement/purchase-orders/template-source";
const sourceBucket = "procurement-po-template-documents";
const allowedSourceTypes = new Set(["application/pdf", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"]);
const maxSourceBytes = 20 * 1024 * 1024;
const formatSize = (bytes: number) => bytes < 1024 * 1024 ? `${Math.max(1, Math.round(bytes / 1024))} KB` : `${(bytes / (1024 * 1024)).toFixed(1)} MB`;

export default function PurchaseOrderTemplatesPage() {
  const { access } = useAccessContext();
  const permissions = access?.permissions || [];
  const readable = access?.roleCodes?.includes("platform_owner") || can(permissions, "procurement_purchase_orders", "view") || can(permissions, "procurement_purchase_orders", "add") || can(permissions, "procurement_purchase_orders", "edit");
  const writable = access?.roleCodes?.includes("platform_owner") || can(permissions, "procurement_purchase_orders", "add") || can(permissions, "procurement_purchase_orders", "edit");
  const [data, setData] = useState<any>({ companies: [], po_templates: [] });
  const [form, setForm] = useState<any>(null);
  const [view, setView] = useState<any>(null);
  const [message, setMessage] = useState("");
  const [messageKind, setMessageKind] = useState<"info" | "success" | "error">("info");
  const [loading, setLoading] = useState(true);
  const [file, setFile] = useState<File | null>(null);

  const load = async () => {
    try { setData(await apiFetch(endpoint)); } catch (error: any) { setMessageKind("error"); setMessage(error.message || "Failed to load PO templates."); } finally { setLoading(false); }
  };
  useEffect(() => { void load(); }, []);

  const companyName = (id: string) => data.companies.find((row: any) => row.id === id)?.company_name || "—";
  const latestVersion = (row: any) => (row.versions || []).slice().sort((a: any, b: any) => Number(b.version_number) - Number(a.version_number))[0];
  const prepareSource = async (selected: File, companyId: string) => { if (!allowedSourceTypes.has(selected.type) || selected.size <= 0 || selected.size > maxSourceBytes) throw new Error("Choose a PDF or DOCX file up to 20 MB."); const organizationId = data.companies.find((company: any) => company.id === companyId)?.organization_id; const prepared = await apiFetch(sourceEndpoint, { method: "POST", body: JSON.stringify({ organization_id: organizationId, company_id: companyId, filename: selected.name, mime_type: selected.type, size_bytes: selected.size }) }); const result = await supabase.storage.from(sourceBucket).uploadToSignedUrl(prepared.path, prepared.token, selected); if (result.error) throw result.error; return { path: prepared.path, original_filename: selected.name, mime_type: selected.type, size_bytes: selected.size }; };
  const request = async (method: string, body: any, success: string) => {
    try { const source = body.kind === "po_template" && file ? await prepareSource(file, body.company_id) : null; if (body.kind === "po_template" && !body.id && !source) throw new Error("A template source PDF or DOCX is required."); await apiFetch(endpoint, { method, body: JSON.stringify(source ? { ...body, source } : body) }); setMessageKind("success"); setMessage(success); setForm(null); setFile(null); setView(null); await load(); } catch (error: any) { setMessageKind("error"); setMessage(error.message || "The PO template action could not be completed."); }
  };
  const toggle = (row: any) => request("PUT", { kind: "po_template", id: row.id, company_id: row.company_id, template_name: row.template_name, template_code: row.template_code, status: row.status === "active" ? "inactive" : "active", is_default: row.is_default }, `Template ${row.status === "active" ? "deactivated" : "activated"}.`);
  const remove = (row: any) => { if (window.confirm(`Delete PO template ${row.template_name}?`)) void request("DELETE", { kind: "po_template", id: row.id, permanent: true }, "PO template deleted."); };

  if (!readable) return <div className="rounded-lg border bg-white p-6 text-sm text-slate-600">Purchase Order templates are not available for your permissions.</div>;

  return <main className="max-w-7xl space-y-6">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><Link href="/settings/purchase-order-masters" className="text-sm font-semibold text-slate-600">Back to Purchase Order Masters</Link><h1 className="mt-2 text-3xl font-bold text-slate-950">Purchase Order Templates</h1><p className="mt-1 text-sm text-slate-500">Manage company-specific Purchase Order layouts and template versions.</p></div>{writable && <button type="button" onClick={() => setForm({ company_id: "", template_name: "", template_code: "", is_default: false })} className="rounded bg-slate-950 px-4 py-2 text-sm font-semibold text-white">Add Template</button>}</header>
    {message && <div className={`rounded-lg border p-3 text-sm ${messageKind === "error" ? "border-red-200 bg-red-50 text-red-800" : messageKind === "success" ? "border-emerald-200 bg-emerald-50 text-emerald-800" : "border-blue-200 bg-blue-50 text-blue-800"}`}>{message}</div>}
    {form && <label className="block rounded-lg border bg-white p-5 text-sm font-semibold">Template File (PDF or DOCX)<input type="file" required={!form.id} accept="application/pdf,.pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,.docx" onChange={(event) => { const selected = event.target.files?.[0] || null; setFile(selected); }} className="mt-2 block w-full rounded border px-3 py-2" />{file && <span className="mt-1 block text-xs font-normal text-slate-500">{file.name} · {file.type === "application/pdf" ? "PDF" : "Word Document"} · {formatSize(file.size)}</span>}<span className="mt-2 block text-xs font-normal text-slate-500">Retained as the template design source; layout mapping and preview are configured before the template becomes ready.</span></label>}
    {form && <form onSubmit={(event) => { event.preventDefault(); void request("POST", { kind: "po_template", ...form }, "PO template created."); }} className="rounded-lg border bg-white p-5 shadow-sm"><h2 className="font-semibold">Add PO Template</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold">Company<select required value={form.company_id} onChange={(event) => setForm({ ...form, company_id: event.target.value })} className="mt-1 h-10 w-full rounded border px-3"><option value="">Select company</option>{data.companies.map((row: any) => <option key={row.id} value={row.id}>{row.company_name}</option>)}</select></label><label className="text-sm font-semibold">Template Name<input required value={form.template_name} onChange={(event) => setForm({ ...form, template_name: event.target.value })} className="mt-1 h-10 w-full rounded border px-3" /></label><label className="text-sm font-semibold">Template Code<input required value={form.template_code} onChange={(event) => setForm({ ...form, template_code: event.target.value.toUpperCase() })} className="mt-1 h-10 w-full rounded border px-3" /></label><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={form.is_default} onChange={(event) => setForm({ ...form, is_default: event.target.checked })} />Set as Default</label></div><p className="mt-3 text-xs text-slate-500">Layout: Not configured. Version 1 is created automatically.</p><div className="mt-4 flex gap-2"><button type="button" onClick={() => setForm(null)} className="rounded border px-4 py-2 text-sm font-semibold">Cancel</button><button className="rounded bg-slate-950 px-4 py-2 text-sm font-semibold text-white">Save Template</button></div></form>}
    {view && <section className="rounded-lg border bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><h2 className="font-semibold">{view.template_name}</h2><p className="text-sm text-slate-500">{view.template_code} · {companyName(view.company_id)}</p></div><button type="button" onClick={() => setView(null)} className="text-sm font-semibold">Close</button></div><dl className="mt-4 grid gap-3 text-sm md:grid-cols-4"><div><dt className="text-slate-500">Status</dt><dd className="font-semibold">{view.status === "active" ? "Active" : "Inactive"}</dd></div><div><dt className="text-slate-500">Default</dt><dd className="font-semibold">{view.is_default ? "Default" : "—"}</dd></div><div><dt className="text-slate-500">Current Version</dt><dd className="font-semibold">{latestVersion(view)?.version_number ? `Version ${latestVersion(view).version_number}` : "—"}</dd></div><div><dt className="text-slate-500">Layout</dt><dd className="font-semibold">{latestVersion(view)?.layout_definition && Object.keys(latestVersion(view).layout_definition).length ? "Configured" : "Not configured"}</dd></div></dl></section>}
    <section className="overflow-x-auto rounded-lg border bg-white shadow-sm"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Template Name", "Company", "Template File", "Status", "Default", "Actions"].map((header) => <th key={header} className="p-3">{header}</th>)}</tr></thead><tbody className="divide-y">{loading ? <tr><td colSpan={6} className="p-8 text-center text-slate-500">Loading PO templates...</td></tr> : !data.po_templates.length ? <tr><td colSpan={6} className="p-8 text-center text-slate-500">No PO templates configured yet.</td></tr> : data.po_templates.map((row: any) => { const version = latestVersion(row); const ready = version?.readiness_status === "ready"; return <tr key={row.id}><td className="p-3 font-semibold">{row.template_name}</td><td className="p-3">{companyName(row.company_id)}</td><td className="p-3">{version?.source_original_filename || "—"}</td><td className="p-3"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${row.status === "inactive" ? "bg-slate-100 text-slate-600" : ready ? "bg-emerald-100 text-emerald-800" : "bg-amber-100 text-amber-800"}`}>{row.status === "inactive" ? "Inactive" : ready ? "Ready" : "Setup Required"}</span></td><td className="p-3">{row.is_default && row.status === "active" ? <span className="rounded-full bg-amber-100 px-2 py-1 text-xs font-semibold text-amber-800">Default</span> : "—"}</td><td className="p-3"><div className="flex flex-wrap gap-2 text-xs font-semibold"><button type="button" onClick={() => setView(row)} className="underline">View</button>{writable && <button type="button" onClick={() => { window.location.href = `/settings/purchase-order-masters/po-templates/configure?id=${row.id}`; }} className="underline">{ready ? "Edit Layout" : "Configure"}</button>}{writable && row.status === "active" && !row.is_default && <button type="button" onClick={() => { if (window.confirm("Set this template as the company default?")) void request("PUT", { kind: "po_template", id: row.id, company_id: row.company_id, template_name: row.template_name, template_code: row.template_code, status: row.status, is_default: true }, "Default template updated."); }} className="underline">Set Default</button>}{writable && <button type="button" onClick={() => void toggle(row)} className="underline">{row.status === "active" ? "Deactivate" : "Activate"}</button>}{writable && <button type="button" onClick={() => remove(row)} className="text-red-700 underline">Delete</button>}</div></td></tr>; })}</tbody></table></section>
  </main>;
}
