import { NextResponse } from "next/server";
import { adminClient, applyOrganizationAccess, jsonError, requireProcurementPermission, text } from "@/lib/serverProcurementAccess";
async function permission(request: Request, action: "view" | "add" | "edit") { return requireProcurementPermission(request, "procurement_site_contact_master", action); }
function siteIsAuthorized(access: any, site: any) {
  const global = access.isGlobalAccess || (access.roleCodes || []).includes("platform_owner");
  if (global) return true;
  if (!(access.organizations || []).includes(site.organization_id)) return false;
  if ((access.sites || []).length > 0 && !(access.sites || []).includes(site.id)) return false;
  return !site.company_id || (access.companies || []).length === 0 || (access.companies || []).includes(site.company_id);
}
async function allowedSiteIds(admin: any, access: any) { const q = applyOrganizationAccess(admin.from("sites").select("id,organization_id,company_id"), access); if (!q) return []; const result = await q; if (result.error) throw result.error; return (result.data || []).filter((site: any) => siteIsAuthorized(access, site)).map((row: any) => row.id); }
export async function GET(request: Request) { try { const access = await permission(request, "view"); if ("response" in access) return access.response; const admin = adminClient(); const siteIds = await allowedSiteIds(admin, access); if (!siteIds.length) return NextResponse.json({ contacts: [] }); const result = await admin.from("site_contacts").select("*").in("site_id", siteIds).order("site_id").order("is_default", { ascending: false }); if (result.error) throw result.error; return NextResponse.json({ contacts: result.data || [] }); } catch (e: any) { return jsonError(e.message || "Failed to load site contacts.", 500); } }
export async function POST(request: Request) { return save(request, "add"); }
export async function PUT(request: Request) { return save(request, "edit"); }
async function save(request: Request, action: "add" | "edit") { try { const access = await permission(request, action); if ("response" in access) return access.response; const body = await request.json().catch(() => ({})); const siteId = text(body.site_id); const contactName = text(body.contact_name); const designation = text(body.designation); const mobile = text(body.mobile); const email = text(body.email); if (!siteId || !contactName || !designation || !mobile || !email) return jsonError("Site, Contact Name, Designation, Mobile and Email are required.", 400); if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) return jsonError("Enter a valid Email address.", 400); const admin = adminClient(); const result = await admin.from("sites").select("id,organization_id,company_id,status").eq("id", siteId).maybeSingle(); if (result.error) throw result.error; if (!result.data) return jsonError("Selected site is outside your access.", 403); const site = result.data; if (site.status !== "active" || !siteIsAuthorized(access, site)) return jsonError("Selected site is outside your access.", 403); const saved = await admin.rpc("save_site_contact_atomic", { p_organization_id: site.organization_id, p_id: text(body.id) || null, p_site_id: siteId, p_contact_name: contactName, p_designation: designation, p_mobile: mobile, p_email: email, p_contact_type: text(body.contact_type) || "other", p_is_default: body.is_default === true, p_status: text(body.status) || "active" }); if (saved.error) throw saved.error; return NextResponse.json({ id: saved.data }); } catch (e: any) { return jsonError(e.message || "Failed to save site contact.", 400); } }
