export const PERMISSION_ACTIONS = [
  "view",
  "create",
  "add",
  "edit",
  "delete",
  "approve",
  "reject",
  "suspend",
  "resume",
  "upload",
  "import",
  "submit",
  "pm_approve",
  "pm_send_back",
  "ho_approve",
  "ho_send_back",
  "final_override",
  "assign_engineer",
  "edit_site_responsibility",
  "edit_attendance_policy",
  "assign_override_authority",
  "change_deployment",
  "change_rate",
  "execute",
  "correct_time",
  "override",
  "mark_paid",
  "export",
] as const;

export type PermissionAction = (typeof PERMISSION_ACTIONS)[number];

const ACTION_LABELS: Record<PermissionAction, string> = {
  view: "View",
  create: "Create",
  add: "Add",
  edit: "Edit",
  delete: "Delete",
  approve: "Approve",
  reject: "Reject",
  suspend: "Suspend",
  resume: "Resume",
  upload: "Upload",
  import: "Import",
  submit: "Submit",
  pm_approve: "PM Approve",
  pm_send_back: "PM Send Back",
  ho_approve: "HO HR Final Approve",
  ho_send_back: "HO HR Send Back",
  final_override: "Final Override",
  assign_engineer: "Assign Engineer",
  edit_site_responsibility: "Edit Site Responsibility",
  edit_attendance_policy: "Edit Attendance Policy",
  assign_override_authority: "Assign Override Authority",
  change_deployment: "Change Deployment",
  change_rate: "Change Rate",
  execute: "Execute",
  correct_time: "Correct Site-In Time",
  override: "Override",
  mark_paid: "Mark Paid",
  export: "Export",
};

const MODULE_ACTIONS: Record<string, PermissionAction[]> = {
  dashboard: ["view"],
  reports: ["view", "export"],

  organizations: ["view", "add", "edit", "delete"],
  users: ["view", "add", "edit", "delete"],
  roles: ["view", "add", "edit"],
  permissions: ["view", "edit"],

  companies: ["view", "add", "edit", "delete"],
  sites: ["view", "add", "edit", "delete"],
  vendors: ["view", "add", "edit", "delete"],
  company_bank_accounts: ["view", "add", "edit", "delete"],

  work_orders: ["view", "add", "edit", "delete", "export"],
  wo_approval: ["view", "edit", "approve", "reject", "upload"],
  ra_bills: ["view", "add", "delete"],
  ra_approval: ["view", "approve", "reject"],
  invoices: ["view", "add", "delete"],
  itc_claims: ["view", "approve", "delete"],
  payments: ["view", "add", "delete"],
  debit_notes: ["view", "add", "delete"],

  hr_employees: ["view", "add", "edit", "delete"],
  hr_departments: ["view", "add", "edit", "delete"],
  hr_designations: ["view", "add", "edit", "delete"],
  hr_attendance: ["view", "add", "edit", "submit", "override", "export"],
  hr_attendance_approval: ["view", "approve", "reject"],
  hr_employee_attendance_policy: ["view", "add", "edit"],
  hr_employee_import: ["view", "upload", "execute", "export"],
  hr_employee_document_import: ["view", "upload", "execute", "export"],
  hr_audit: ["view"],
  hr_salary: ["view", "add", "edit", "delete"],
  reimbursements: [
    "view",
    "add",
    "edit",
    "delete",
    "upload",
    "submit",
    "approve",
    "reject",
    "mark_paid",
  ],
  labour_contractors: ["view", "add", "edit", "delete", "upload", "export"],
  labour_workers: ["view", "add", "edit", "delete", "upload", "import", "export", "change_deployment", "change_rate"],
  labour_deployments: ["view", "add", "edit", "export"],
  labour_import: ["view", "upload", "execute", "export"],
  labour_documents: ["view", "upload", "delete"],
  labour_trades: ["view", "add", "edit", "delete", "export"],
  labour_attendance: ["view", "add", "edit", "submit", "override", "export"],
  labour_attendance_approval: ["view", "approve"],
  labour_attendance_import: ["view", "upload", "execute", "export"],
  labour_wage_rates: ["view", "add", "edit", "delete", "export"],
  labour_wages: ["view", "add", "edit", "submit", "export"],
  labour_wage_approval: ["view", "approve", "reject"],
  labour_advances: ["view", "add", "edit", "delete", "approve", "export"],
  labour_manpower_work_orders: ["view", "add", "edit", "delete", "submit", "approve", "reject", "suspend", "resume", "upload", "export"],
  labour_attendance_policy: ["view", "edit", "override"],
  labour_attendance_unlock: ["view", "approve"],
  labour_site_in: ["view", "add", "correct_time"],
  labour_engineer_daily: ["view", "add", "edit", "submit"],
  labour_muster_configuration: ["view", "edit_site_responsibility", "edit_attendance_policy", "assign_override_authority", "export"],
  labour_engineer_groups: ["view", "create", "edit", "delete"],
  labour_work_groups: ["view", "add", "edit", "delete", "submit", "approve", "export"],
  labour_work_logs: ["view", "add", "edit", "delete", "submit", "approve", "reject", "assign_engineer", "upload", "export"],
  labour_daily_submission: ["view", "submit", "pm_approve", "pm_send_back", "ho_approve", "ho_send_back", "final_override", "export"],
  labour_overtime: ["view", "add", "edit", "approve", "reject", "export"],
  labour_photo_evidence: ["view", "upload", "edit", "delete"],
  labour_rate_overrides: ["view", "add", "edit", "delete", "approve", "export"],
};

export function permissionActionLabel(actionCode: string) {
  return ACTION_LABELS[actionCode as PermissionAction] || actionCode;
}

export function availableActionsForModule(moduleCode: string): PermissionAction[] {
  return MODULE_ACTIONS[moduleCode] || ["view"];
}

export function isValidPermissionAction(moduleCode: string, actionCode: string) {
  return availableActionsForModule(moduleCode).includes(actionCode as PermissionAction);
}
