import { NextResponse } from "next/server";
import { adminClient, applyOrganizationAccess, jsonError, requireProcurementPermission, text } from "@/lib/serverProcurementAccess";
import { recordAuditEvent } from "@/lib/auditEvent";

async function permission(request: Request, action: "view" | "add" | "edit") { return requireProcurementPermission(request, "procurement_gst_billing_delivery_master", action); }
function scoped(query: any, access: any) { const q = applyOrganizationAccess(query, access); if (!q) return null; if (access.isGlobalAccess || (access.roleCodes || []).includes("platform_owner")) return q; return (access.companies || []).length ? q.in("company_id", access.companies) : null; }
export async function GET(request: Request) { try { const access = await permission(request, "view"); if ("response" in access) return access.response; const q = scoped(adminClient().from("company_gst_registrations").select("*").order("company_id").order("is_default", { ascending: false }), access); if (!q) return NextResponse.json({ registrations: [] }); const result = await q; if (result.error) throw result.error; return NextResponse.json({ registrations: result.data || [] }); } catch (e: any) { return jsonError(e.message || "Failed to load GST registrations.", 500); } }
export async function POST(request: Request) { return save(request, "add"); }
export async function PUT(request: Request) { return save(request, "edit"); }
async function save(request: Request, action: "add" | "edit") { try { const access = await permission(request, action); if ("response" in access) return access.response; const body = await request.json().catch(() => ({})); const companyId = text(body.company_id); const admin = adminClient(); const result = await admin.from("companies").select("id,organization_id,status").eq("id", companyId).maybeSingle(); if (result.error) throw result.error; if (!result.data) return jsonError("Selected company is outside your access.", 403); const company = result.data; const global = access.isGlobalAccess || (access.roleCodes || []).includes("platform_owner"); if (company.status !== "active" || (!global && (!(access.organizations || []).includes(company.organization_id) || ((access.companies || []).length > 0 && !access.companies.includes(companyId))))) return jsonError("Selected company is outside your access.", 403); const saved = await admin.rpc("save_company_gst_registration_atomic", { p_organization_id: company.organization_id, p_id: text(body.id) || null, p_company_id: companyId, p_gstin: text(body.gstin), p_legal_name: text(body.legal_name) || null, p_trade_name: text(body.trade_name) || null, p_state: text(body.state) || null, p_state_code: text(body.state_code) || null, p_registration_type: text(body.registration_type) || null, p_effective_from: text(body.effective_from) || null, p_effective_to: text(body.effective_to) || null, p_is_default: body.is_default === true, p_status: text(body.status) || "active" }); if (saved.error) throw saved.error; await recordAuditEvent(admin, access.user, { organizationId: company.organization_id, companyId, moduleCode: "procurement_gst_billing_delivery_master", entityType: "gst_registration", recordId: saved.data, action, actionCategory: action === "add" ? "create" : "update", activityLabel: `${action === "add" ? "Created" : "Updated"} GST Registration`, description: `${action === "add" ? "Created" : "Updated"} GST registration for ${text(body.gstin)}.`, newValues: body }, request); return NextResponse.json({ id: saved.data }); } catch (e: any) { return jsonError(e.message || "Failed to save GST registration.", 400); } }
