"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, Eye, PlayCircle, Plus } from "lucide-react";
import { useParams } from "next/navigation";
import AlertMessage from "@/components/AlertMessage";
import { apiFetch } from "@/components/hr/hrClient";

function qty(value: unknown) { return Number(value || 0).toLocaleString("en-IN", { maximumFractionDigits: 3 }); }
function money(value: unknown) { return `Rs ${Number(value || 0).toLocaleString("en-IN")}`; }
function statusClass(status: string) { return status === "Fully Received" ? "border-emerald-200 bg-emerald-50 text-emerald-800" : status === "Partially Received" ? "border-amber-200 bg-amber-50 text-amber-800" : status === "Receipt In Progress" ? "border-sky-200 bg-sky-50 text-sky-800" : "border-slate-200 bg-slate-50 text-slate-700"; }
function poStatus(status: unknown) { return String(status || "").replace(/_/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function grnStatus(status: string) { return status === "finalized" ? "Finalized" : "Draft"; }

export default function GoodsReceiptPurchaseOrderHistoryPage() {
  const { id } = useParams<{ id: string }>();
  const [data, setData] = useState<any>(null);
  const [message, setMessage] = useState("");
  useEffect(() => { apiFetch(`/api/procurement/goods-receipts/purchase-orders/${id}`).then(setData).catch((error: any) => setMessage(error.message)); }, [id]);
  if (!data) return <section className="space-y-4"><Link href="/store/goods-receipts" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-600"><ArrowLeft className="h-4 w-4" />Back to Purchase Order Tracking</Link><AlertMessage type="error" message={message} onClose={() => setMessage("")} /><p className="text-sm text-slate-500">{message ? "" : "Loading Purchase Order tracking..."}</p></section>;
  const po = data.purchase_order;
  const draftReceipt = (data.grns || []).find((grn: any) => grn.status === "draft");
  const canCreate = data.receipt_status !== "Fully Received";
  const timeline = (data.grns || []).filter((grn: any) => grn.created_at || grn.finalized_at);
  return <section className="space-y-6">
    <Link href="/store/goods-receipts" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-600 hover:text-slate-950"><ArrowLeft className="h-4 w-4" />Back to Purchase Order Tracking</Link>
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase text-emerald-700">Purchase Order Tracking</p><h1 className="mt-1 text-3xl font-bold">{po.po_number}</h1><p className="text-sm text-slate-500">{po.company?.company_name || "-"} · {po.site?.site_name || "-"} · {po.vendor_name_snapshot || "-"}</p>{draftReceipt && <p className="mt-2 text-sm font-semibold text-sky-700">Draft receipt {draftReceipt.grn_number} in progress</p>}</div><div className="flex flex-wrap items-center gap-3"><span className={`whitespace-nowrap rounded-full border px-3 py-1 text-xs font-semibold ${statusClass(data.receipt_status)}`}>{data.receipt_status}</span>{draftReceipt ? <Link href={`/store/goods-receipts/${draftReceipt.id}`} className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-2 text-sm font-semibold text-white"><PlayCircle className="h-4 w-4" />Continue Receipt</Link> : canCreate && <Link href={`/store/goods-receipts/new?purchase_order_id=${po.id}`} className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-2 text-sm font-semibold text-white"><Plus className="h-4 w-4" />Record Receipt</Link>}</div></header>
    <AlertMessage type="error" message={message} onClose={() => setMessage("")} />
    <section className="grid gap-4 rounded-xl border bg-white p-5 shadow-sm md:grid-cols-6"><div><p className="text-xs font-semibold uppercase text-slate-500">Company</p><p className="mt-1 font-semibold">{po.company?.company_name || "-"}</p></div><div><p className="text-xs font-semibold uppercase text-slate-500">Site</p><p className="mt-1 font-semibold">{po.site?.site_name || "-"}</p></div><div><p className="text-xs font-semibold uppercase text-slate-500">Vendor</p><p className="mt-1 font-semibold">{po.vendor_name_snapshot || "-"}</p></div><div><p className="text-xs font-semibold uppercase text-slate-500">PO Date</p><p className="mt-1 font-semibold">{po.po_date || "-"}</p></div><div><p className="text-xs font-semibold uppercase text-slate-500">PO Amount</p><p className="mt-1 font-semibold">{money(po.total_amount)}</p></div><div><p className="text-xs font-semibold uppercase text-slate-500">PO Status</p><p className="mt-1 font-semibold">{poStatus(po.status)}</p></div></section>
    <section className="grid gap-3 md:grid-cols-6">{[["PO Quantity", data.totals?.po_quantity], ["Total Received", data.totals?.received], ["Accepted", data.totals?.accepted], ["Rejected", data.totals?.rejected], ["Hold", data.totals?.hold], ["Remaining", data.totals?.remaining]].map(([title, value]) => <div key={title} className="rounded-xl border bg-white p-4 shadow-sm"><p className="text-xs font-semibold uppercase text-slate-500">{title}</p><p className="mt-2 text-xl font-bold text-slate-950">{qty(value)}</p></div>)}</section>
    <section className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="font-semibold">Material-wise Tracking</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Material", "Specification", "UOM", "PO Qty", "Received", "Accepted", "Rejected", "Hold", "Remaining to Accept", "Status"].map((heading) => <th key={heading} className="p-3">{heading}</th>)}</tr></thead><tbody className="divide-y">{po.items.map((item: any) => <tr key={item.id}><td className="p-3 font-semibold">{item.item_name_snapshot}</td><td className="p-3">{item.specification_snapshot || "-"}</td><td className="p-3">{item.uom_snapshot || "-"}</td><td className="p-3">{qty(item.quantity)}</td><td className="p-3">{qty(item.received_to_date)}</td><td className="p-3">{qty(item.accepted_to_date)}</td><td className="p-3">{qty(item.rejected_to_date)}</td><td className="p-3">{qty(item.hold_to_date)}</td><td className="p-3 font-semibold">{qty(item.remaining_quantity)}</td><td className="p-3"><span className={`whitespace-nowrap rounded-full border px-2 py-1 text-xs font-semibold ${statusClass(item.receipt_status)}`}>{item.receipt_status}</span></td></tr>)}</tbody></table></div></section>
    <section className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="font-semibold">Goods Receipts / Receipt History</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[1250px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["GRN / Receipt Number", "Receipt Date", "Vehicle", "Received", "Accepted", "Rejected", "Hold", "Status", "Created / Finalized By", "Action"].map((heading) => <th key={heading} className="p-3">{heading}</th>)}</tr></thead><tbody className="divide-y">{data.grns.length === 0 ? <tr><td colSpan={10} className="p-6 text-center text-slate-500">No receipt transactions found.</td></tr> : data.grns.map((grn: any) => <tr key={grn.id}><td className="p-3 font-semibold">{grn.grn_number}</td><td className="p-3">{grn.received_date || grn.grn_date || "-"}</td><td className="p-3">{grn.vehicle_number || "-"}</td><td className="p-3">{qty(grn.totals?.received)}</td><td className="p-3">{qty(grn.totals?.accepted)}</td><td className="p-3">{qty(grn.totals?.rejected)}</td><td className="p-3">{qty(grn.totals?.hold)}</td><td className="p-3"><span className={`rounded-full border px-2 py-1 text-xs font-semibold ${grn.status === "finalized" ? "border-emerald-200 bg-emerald-50 text-emerald-800" : "border-sky-200 bg-sky-50 text-sky-800"}`}>{grnStatus(grn.status)}</span></td><td className="p-3"><div>{grn.created_by_name || "-"}</div><div className="text-xs text-slate-500">{grn.finalized_by_name || ""}</div></td><td className="p-3"><Link href={`/store/goods-receipts/${grn.id}`} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-semibold"><Eye className="h-4 w-4" />View</Link></td></tr>)}</tbody></table></div></section>
    {timeline.length > 0 && <section className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="font-semibold">Receipt Timeline</h2><div className="mt-4 space-y-3">{timeline.map((grn: any) => <div key={grn.id} className="border-l-2 border-slate-200 pl-4 text-sm"><p className="font-semibold">{grn.grn_number} · {grnStatus(grn.status)}</p><p className="text-slate-500">Created {grn.created_at || "-"}{grn.finalized_at ? ` · Finalized ${grn.finalized_at}` : ""}</p></div>)}</div></section>}
  </section>;
}
