"use client";
import { useEffect, useState } from "react";
import PlatformShell from "../PlatformShell";
import { supabase } from "@/lib/supabase";
type Permission = { module_code: string; action_code: string };
type Template = { id: string; name: string; description: string | null; status: string; is_default: boolean; is_tenant_admin_template: boolean; applicable_modules: string[]; permissions: Permission[] };
export default function RoleTemplatesPage() {
  const [templates, setTemplates] = useState<Template[] | null>(null); const [error, setError] = useState("");
  useEffect(() => { void (async () => { const { data: { session } } = await supabase.auth.getSession(); const response = await fetch("/api/platform/role-templates", { headers: { Authorization: `Bearer ${session?.access_token || ""}` } }); const value = await response.json(); if (!response.ok) setError(value.error || "Unable to load role templates."); else setTemplates(value.templates || []); })(); }, []);
  return <PlatformShell><div className="mb-8"><p className="text-sm font-semibold text-slate-500">SITEQUBE PLATFORM / ACCESS</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Default Roles &amp; Permissions</h1><p className="mt-2 max-w-2xl text-slate-500">Read-only defaults for future managed tenants. Existing tenant and MRC roles remain independent.</p></div>{error && <div role="alert" className="mb-4 rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}{templates === null ? <div className="rounded-xl border bg-white p-6">Loading templates...</div> : templates.length === 0 ? <div className="rounded-xl border bg-white p-6 text-sm text-slate-500">No active default role templates configured.</div> : <div className="grid gap-4">{templates.map((template) => <article key={template.id} className="rounded-xl border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">{template.name}</h2><p className="mt-1 text-sm text-slate-500">{template.description || "No description"}</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700">{template.status}</span></div><div className="mt-4 flex flex-wrap gap-2 text-xs text-slate-600"><span className="rounded-full bg-slate-100 px-2.5 py-1">{template.permissions.length} permissions</span>{template.is_default && <span className="rounded-full bg-amber-50 px-2.5 py-1 text-amber-700">System default</span>}{template.is_tenant_admin_template && <span className="rounded-full bg-blue-50 px-2.5 py-1 text-blue-700">Tenant administrator</span>}{template.applicable_modules.map((module) => <span key={module} className="rounded-full bg-slate-100 px-2.5 py-1">{module}</span>)}</div></article>)}</div>}</PlatformShell>;
}
