import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { PDFDocument } from "pdf-lib";
import { requirePermission } from "@/lib/serverPermissions";
import { isRevisionSchemaUnavailable, sha256 } from "@/lib/workOrderPilotRevisions.server";

function db() { return createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!); }
async function load(id: string, revisionId: string) {
  const admin = db(); const { data, error } = await admin.from("work_order_pilot_revisions").select("*, work_orders!inner(creation_request_id,organization_id,approval_status,company_id,site_id,wo_number)").eq("id", revisionId).eq("work_order_id", id).maybeSingle();
  if (error) throw error; if (!data || !data.work_orders?.creation_request_id) return null;
  const { data: vendorLink, error: vendorError } = await admin.from("work_order_vendors").select("vendor_id,vendor_role").eq("work_order_id", id).eq("is_primary", true).maybeSingle();
  if (vendorError) throw vendorError;
  return { admin, revision: { ...data, work_orders: { ...data.work_orders, vendor_id: vendorLink?.vendor_id || null, vendor_role: vendorLink?.vendor_role || "Main Contractor" } } };
}

export async function GET(request: Request, { params }: { params: Promise<{ id: string; revisionId: string }> }) {
  try { const auth = await requirePermission(request, "work_orders", "view"); if ("response" in auth) return auth.response; const { id, revisionId } = await params; const found = await load(id, revisionId); if (!found) return NextResponse.json({ error: "Pilot revision not found." }, { status: 404 }); return NextResponse.json({ revision: found.revision }); }
  catch (e: any) { if (isRevisionSchemaUnavailable(e)) return NextResponse.json({ error: "Pilot Work Order revisions are not available because the revision schema has not been installed in this database." }, { status: 503 }); return NextResponse.json({ error: e.message || "Failed to load revision." }, { status: 500 }); }
}

export async function PATCH(request: Request, { params }: { params: Promise<{ id: string; revisionId: string }> }) {
  try { const auth = await requirePermission(request, "work_orders", "edit"); if ("response" in auth) return auth.response; const { id, revisionId } = await params; const found = await load(id, revisionId); if (!found) return NextResponse.json({ error: "Pilot revision not found." }, { status: 404 }); if (found.revision.status !== "draft") return NextResponse.json({ error: "Submitted revisions are immutable." }, { status: 409 }); const body = await request.json(); if (!body.snapshot || !/^\d{4}-\d{2}-\d{2}$/.test(String(body.applicable_date || found.revision.applicable_date))) return NextResponse.json({ error: "A valid Applicable Date and snapshot are required." }, { status: 400 }); const fields = body.snapshot.fields || {}; const order = found.revision.work_orders; if (fields.company_id !== order.company_id || fields.site_id !== order.site_id || fields.vendor_id !== order.vendor_id || fields.wo_number !== order.wo_number) return NextResponse.json({ error: "Company, Site, Vendor, and Work Order number cannot be changed in a revision." }, { status: 409 }); const snapshotHash = sha256(Buffer.from(JSON.stringify(body.snapshot))); const { data, error } = await found.admin.from("work_order_pilot_revisions").update({ snapshot: body.snapshot, snapshot_sha256: snapshotHash, applicable_date: body.applicable_date || found.revision.applicable_date, updated_at: new Date().toISOString() }).eq("id", revisionId).eq("status", "draft").select("*").single(); if (error) throw error; return NextResponse.json({ revision: data }); }
  catch (e: any) { if (isRevisionSchemaUnavailable(e)) return NextResponse.json({ error: "Pilot Work Order revisions are not available because the revision schema has not been installed in this database." }, { status: 503 }); return NextResponse.json({ error: e.message || "Failed to update revision draft." }, { status: 500 }); }
}

export async function POST(request: Request, { params }: { params: Promise<{ id: string; revisionId: string }> }) {
  try {
    const body = await request.json().catch(() => ({})); const action = String(body.action || "");
    const auth = await requirePermission(request, "work_orders", ["approve", "send_back"].includes(action) ? "approve" : "edit"); if ("response" in auth) return auth.response;
    const { id, revisionId } = await params; const found = await load(id, revisionId); if (!found) return NextResponse.json({ error: "Pilot revision not found." }, { status: 404 });
    const revision = found.revision;
    if (action === "submit") { if (revision.status !== "draft") return NextResponse.json({ revision }); const { data: artifact } = await found.admin.from("work_order_pilot_revision_artifacts").select("*").eq("revision_id", revisionId).maybeSingle(); if (!artifact) return NextResponse.json({ error: "The reviewed Pilot revision PDF artifact is required before submission." }, { status: 409 }); const stored = await found.admin.storage.from(artifact.storage_bucket).download(artifact.storage_path); if (stored.error || !stored.data) return NextResponse.json({ error: "The reviewed Pilot revision PDF artifact could not be verified." }, { status: 409 }); const bytes = Buffer.from(await stored.data.arrayBuffer()); const pdf = await PDFDocument.load(bytes); if (sha256(bytes) !== artifact.sha256 || bytes.length !== Number(artifact.byte_length) || pdf.getPageCount() !== Number(artifact.page_count)) return NextResponse.json({ error: "The reviewed Pilot revision PDF artifact failed integrity verification." }, { status: 409 }); const { data, error } = await found.admin.from("work_order_pilot_revisions").update({ status: "submitted", submitted_at: new Date().toISOString() }).eq("id", revisionId).eq("status", "draft").select("*").single(); if (error) throw error; return NextResponse.json({ revision: data }); }
    if (action === "approve") { if (revision.status !== "submitted") return NextResponse.json({ error: "Only submitted revisions can be approved." }, { status: 409 }); const { data, error } = await found.admin.rpc("approve_work_order_pilot_revision", { p_revision_id: revisionId }); if (error) throw error; return NextResponse.json({ revision: data }); }
    if (action === "send_back") { if (revision.status !== "submitted") return NextResponse.json({ error: "Only submitted revisions can be sent back." }, { status: 409 }); const comment = String(body.comment || "").trim(); if (!comment) return NextResponse.json({ error: "A send-back comment is required." }, { status: 400 }); const { data, error } = await found.admin.from("work_order_pilot_revisions").update({ status: "draft", send_back_comment: comment, sent_back_at: new Date().toISOString() }).eq("id", revisionId).eq("status", "submitted").select("*").single(); if (error) throw error; return NextResponse.json({ revision: data }); }
    if (action === "artifact") { if (!["draft", "submitted"].includes(revision.status)) return NextResponse.json({ error: "Artifact cannot be replaced after approval." }, { status: 409 }); const bytes = Buffer.from(String(body.base64 || ""), "base64"); const pdf = await PDFDocument.load(bytes); if (!bytes.length || pdf.getPageCount() < 1) return NextResponse.json({ error: "A valid reviewed PDF artifact is required." }, { status: 400 }); const path = `structured-pilot/${id}/revisions/${revisionId}/reviewed-package.pdf`; const uploaded = await found.admin.storage.from("work-order-documents").upload(path, bytes, { contentType: "application/pdf", upsert: false }); if (uploaded.error && !String(uploaded.error.message).toLowerCase().includes("already exists")) throw uploaded.error; const { data: artifact, error } = await found.admin.from("work_order_pilot_revision_artifacts").upsert({ revision_id: revisionId, organization_id: revision.organization_id, storage_path: path, sha256: sha256(bytes), byte_length: bytes.length, page_count: pdf.getPageCount() }, { onConflict: "revision_id" }).select("*").single(); if (error) throw error; return NextResponse.json({ artifact }); }
    return NextResponse.json({ error: "Unsupported revision action." }, { status: 400 });
  } catch (e: any) { if (isRevisionSchemaUnavailable(e)) return NextResponse.json({ error: "Pilot Work Order revisions are not available because the revision schema has not been installed in this database." }, { status: 503 }); return NextResponse.json({ error: e.message || "Revision action failed." }, { status: 500 }); }
}
