"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { apiFetch } from "@/components/hr/hrClient";
import AlertMessage from "@/components/AlertMessage";
import LetterheadAssetUpload from "./LetterheadAssetUpload";


export default function LetterheadsPage() {
  const [rows, setRows] = useState<any[]>([]); const [companies, setCompanies] = useState<any[]>([]); const [form, setForm] = useState<any>(null); const [preview, setPreview] = useState<any>(null); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function load() { const [letterheads, masters] = await Promise.all([apiFetch("/api/procurement/purchase-orders/letterheads"), apiFetch("/api/procurement/purchase-orders/master-data")]); setRows(letterheads.letterheads || []); setCompanies(masters.companies || []); }
  useEffect(() => { void load().catch((e) => setError(e.message || "Could not load Letterheads.")); }, []);
  function feedback(next: string, failed = false) { setError(failed ? next : ""); setMessage(failed ? "" : next); }
  async function create(event: React.FormEvent) { event.preventDefault(); try { const body = new FormData(); body.set("company_id", form.company_id); body.set("letterhead_name", form.letterhead_name); const result = await apiFetch("/api/procurement/purchase-orders/letterheads", { method: "POST", body }); setForm({ ...form, id: result.id, version_id: result.version_id, header_height_points: 150, footer_height_points: 125, content_margin_left_points: 42, content_margin_right_points: 42, content_gap_after_header_points: 8, content_gap_before_footer_points: 8 }); feedback("Letterhead draft created."); await load(); } catch (e: any) { feedback(e.message || "Could not create Letterhead.", true); } }
  async function save(event: React.FormEvent) { event.preventDefault(); try { const body = new FormData(); body.set("version_id", form.version_id); if (form.header) body.set("header", form.header); if (form.footer) body.set("footer", form.footer); await apiFetch("/api/procurement/purchase-orders/letterheads", { method: "PUT", body }); feedback("Letterhead draft saved."); setForm(null); await load(); } catch (e: any) { feedback(e.message || "Could not save Letterhead draft.", true); } }
  async function action(versionId: string, name: string) { try { await apiFetch("/api/procurement/purchase-orders/letterheads", { method: "PATCH", body: JSON.stringify({ version_id: versionId, action: name }) }); feedback(name === "ready" ? "Letterhead marked Ready." : name === "default" ? "Letterhead made default." : name === "new_version" ? "New Letterhead draft created." : "Letterhead status updated."); await load(); } catch (e: any) { feedback(e.message || "Could not update Letterhead.", true); } }
  async function removeDraft(versionId: string) { if (!window.confirm("Delete this unused Draft Letterhead? This action cannot be undone.")) return; try { await apiFetch("/api/procurement/purchase-orders/letterheads", { method: "DELETE", body: JSON.stringify({ version_id: versionId }) }); feedback("Unused Draft Letterhead deleted."); await load(); } catch (e: any) { feedback(e.message || "Could not delete Draft Letterhead.", true); } }
  async function removeOrphan(letterheadId: string) { if (!window.confirm("Delete this unused Letterhead Master? This action cannot be undone.")) return; try { await apiFetch("/api/procurement/purchase-orders/letterheads", { method: "DELETE", body: JSON.stringify({ letterhead_id: letterheadId }) }); feedback("Unused Letterhead Master deleted."); await load(); } catch (e: any) { feedback(e.message || "Could not delete Letterhead Master.", true); } }
  async function showPreview(version: any) { try { const result = await apiFetch(`/api/procurement/purchase-orders/letterheads?version_id=${version.id}`); setPreview({ ...result, version }); } catch (e: any) { feedback(e.message || "Could not load preview.", true); } }
  return <main className="w-full space-y-6"><header><Link href="/modules/settings" className="text-sm font-semibold text-slate-600">Back to Masters</Link><h1 className="mt-2 text-3xl font-bold text-slate-950">Letterhead Master</h1><p className="mt-1 text-sm text-slate-500">Manage original PNG stationery for generated Purchase Orders.</p></header><AlertMessage type="success" message={message} onClose={() => setMessage("")} /><AlertMessage type="error" message={error} onClose={() => setError("")} />
    {!form && <><button type="button" onClick={() => setForm({ company_id: "", letterhead_name: "" })} className="rounded bg-slate-950 px-4 py-2 text-sm font-semibold text-white">+ Add Letterhead</button><div className="overflow-x-auto rounded border bg-white"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-slate-50"><tr>{["Letterhead Name", "Company", "Current Version", "Version Status", "Active", "Default", "Header", "Footer", "Updated", "Actions"].map((heading) => <th key={heading} className="p-3">{heading}</th>)}</tr></thead><tbody>{rows.map((row) => { const versions = (row.versions || []).slice().sort((a: any, b: any) => b.version_number - a.version_number); const version = versions[0]; const ready = version?.version_status === "ready"; const deletable = version?.version_status === "draft" && !row.is_default; const orphanDeletable = !version && row.status === "inactive" && !row.is_default; return <tr key={row.id} className="border-t"><td className="p-3 font-semibold">{row.letterhead_name}</td><td className="p-3">{row.company?.company_name || "—"}</td><td className="p-3">{version ? `Version ${version.version_number}` : "—"}</td><td className="p-3">{version?.version_status || "Draft"}</td><td className="p-3">{row.status === "active" ? "Active" : "Inactive"}</td><td className="p-3">{row.is_default ? "Default" : "—"}</td><td className="p-3">{version?.header_storage_key ? "✓" : "—"}</td><td className="p-3">{version?.footer_storage_key ? "✓" : "—"}</td><td className="p-3">{version?.created_at ? new Date(version.created_at).toLocaleDateString("en-IN") : "—"}</td><td className="p-3"><div className="flex flex-wrap gap-2 text-xs font-semibold">{version && <button type="button" onClick={() => showPreview(version)} className="underline">Preview</button>}{version && !ready && <><button type="button" onClick={() => setForm({ ...row, ...version, version_id: version.id })} className="underline">Edit</button><button type="button" onClick={() => action(version.id, "ready")} className="underline">Mark Ready</button></>}{version && ready && <><button type="button" onClick={() => action(version.id, "new_version")} className="underline">New Version</button>{!row.is_default && <button type="button" onClick={() => action(version.id, "default")} className="underline">Make Default</button>}</>}{version && <button type="button" onClick={() => action(version.id, "toggle")} className="text-red-700 underline">{row.status === "active" ? "Deactivate" : "Activate"}</button>}{deletable && <button type="button" onClick={() => removeDraft(version.id)} className="text-red-700 underline">Delete</button>}{orphanDeletable && <button type="button" onClick={() => removeOrphan(row.id)} className="text-red-700 underline">Delete</button>}</div></td></tr>; })}</tbody></table></div></>}
    {form && (!form.id ? <form onSubmit={create} className="max-w-xl space-y-4 rounded border bg-white p-5"><h2 className="text-lg font-semibold">Add Letterhead</h2><label className="block text-sm font-semibold">Company<select required value={form.company_id} onChange={(e) => setForm({ ...form, company_id: e.target.value })} className="mt-1 h-10 w-full rounded border px-3"><option value="">Select company</option>{companies.map((company) => <option key={company.id} value={company.id}>{company.company_name}</option>)}</select></label><label className="block text-sm font-semibold">Letterhead Name<input required value={form.letterhead_name} onChange={(e) => setForm({ ...form, letterhead_name: e.target.value })} className="mt-1 h-10 w-full rounded border px-3" /></label><button className="rounded bg-slate-950 px-4 py-2 text-sm font-semibold text-white">Create Draft</button></form> : <form onSubmit={save} className="max-w-2xl space-y-4 rounded border bg-white p-5"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Edit Letterhead Draft</h2><button type="button" onClick={() => setForm(null)} className="text-sm underline">Cancel</button></div><p className="text-sm text-slate-600">{form.letterhead_name} · {form.company?.company_name || "Company"} · Version {form.version_number}</p><div className="grid gap-4 sm:grid-cols-2"><LetterheadAssetUpload label="Header" value={form.header} onChange={(file) => setForm({ ...form, header: file })} /><LetterheadAssetUpload label="Footer" value={form.footer} onChange={(file) => setForm({ ...form, footer: file })} /></div><button className="rounded bg-slate-950 px-4 py-2 text-sm font-semibold text-white">Save Draft</button></form>)}
    {preview && <div className="fixed inset-0 z-50 overflow-auto bg-slate-950/40 p-6"><div className="mx-auto max-w-[900px] rounded bg-white p-5"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Letterhead Preview · Version {preview.version.version_number}</h2><button type="button" onClick={() => setPreview(null)} className="text-sm underline">Close</button></div><div className="mx-auto mt-5 aspect-[210/297] max-w-[620px] border bg-white shadow"><div className="flex min-h-[22%] items-center justify-center bg-slate-50 text-center text-xs text-slate-500">{preview.urls.header ? <img src={preview.urls.header} alt="Header preview" className="h-auto max-h-full w-full object-contain object-top" /> : "Upload a Header PNG to preview the Letterhead."}</div><div className="mx-[6%] mt-4 border border-dashed border-slate-300 p-5 text-center text-sm text-slate-500">Safe PO content area</div><div className="mt-[18%] flex min-h-[16%] items-center justify-center bg-slate-50 text-center text-xs text-slate-500">{preview.urls.footer ? <img src={preview.urls.footer} alt="Footer preview" className="h-auto max-h-full w-full object-contain object-bottom" /> : "Upload a Footer PNG to preview the Letterhead."}</div></div></div></div>}
  </main>;
}
